#!/usr/bin/env python3
"""Generate documentation/pinout.svg and the README pin table from the CubeMX .ioc.

Run from anywhere: paths are resolved relative to the repo root. Invoked by the
pre-commit hook whenever the .ioc is staged, so the diagram and table can never
drift from the actual pin configuration.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
README = REPO_ROOT / "README.md"
SVG_OUT = REPO_ROOT / "documentation" / "pinout.svg"
FIRMWARE_DIR = REPO_ROOT / "firmware"

BEGIN_MARK = "<!-- PINOUT:BEGIN (auto-generated by tools/pinout/generate_pinout.py, do not edit by hand) -->"
END_MARK = "<!-- PINOUT:END -->"

# Physical layouts, viewed from the top of the package. Order is exactly as
# drawn: left/right top->bottom, top/bottom left->right. Names are pad names;
# .ioc keys for the oscillator pins differ (see IOC_ALIASES).
LAYOUTS = {
    "UFQFPN48": {
        "left": ["VBAT", "PC13", "PC14", "PC15", "PF0", "PF1", "PG10", "PA0", "PA1", "PA2", "PA3", "PA4"],
        "bottom": ["PA5", "PA6", "PA7", "PC4", "PB0", "PB1", "PB2", "VREF+", "VDDA", "PB10", "VDD", "PB11"],
        "right": ["PA13", "VDD", "PA12", "PA11", "PA10", "PA9", "PA8", "PC6", "PB15", "PB14", "PB13", "PB12"],
        "top": ["VDD", "PB9", "PB8", "PB7", "PB6", "PB5", "PB4", "PB3", "PC11", "PC10", "PA15", "PA14"],
    },
    "LQFP64": {
        "left": ["VBAT", "PC13", "PC14", "PC15", "PF0", "PF1", "PG10", "PC0", "PC1", "PC2", "PC3", "PA0", "PA1", "PA2", "PA3", "VSS"],
        "bottom": ["VDD", "PA4", "PA5", "PA6", "PA7", "PC4", "PC5", "PB0", "PB1", "PB2", "PB10", "VREF+", "VDDA", "VSSA", "VDD", "VSS"],
        "right": ["VDD", "VSS", "PA12", "PA11", "PA10", "PA9", "PA8", "PC9", "PC8", "PC7", "PC6", "PB15", "PB14", "PB13", "PB12", "PB11"],
        "top": ["VDD", "VSS", "PB9", "PB8", "PB7", "PB6", "PB5", "PB4", "PB3", "PD2", "PC12", "PC11", "PC10", "PA15", "PA14", "PA13"],
    },
}

IOC_ALIASES = {
    "PC14": "PC14-OSC32_IN",
    "PC15": "PC15-OSC32_OUT",
    "PF0": "PF0-OSC_IN",
    "PF1": "PF1-OSC_OUT",
    "PG10": "PG10-NRST",
}

POWER_PINS = {"VBAT", "VDD", "VDDA", "VREF+", "VSS", "VSSA"}

# Fixed system roles shown even when the pin carries no .ioc signal.
SYSTEM_ROLES = {"PG10": "NRST", "PB8": "BOOT0"}

# Bus groups: id -> (legend text, signal prefixes, label names/prefixes)
GROUPS = [
    ("spi1", "SPI1 · EXT", ("SPI1_",), ("SPI1_CS", "SPI1_INT")),
    ("spi2", "SPI2 · IMU", ("SPI2_",), ("SPI2_CS", "SPI2_INT", "FSYNC")),
    ("i2c1", "I2C1 · TOF", ("I2C1_",), ("XSHUT",)),
    ("motor", "MOTORS · TIM3", ("S_TIM3_",), ("MOTOR_",)),
    ("servo", "SERVOS · TIM1", ("S_TIM1_",), ("SERV_",)),
    ("pwm", "PWM · TIM2", ("S_TIM2_",), ("PWM_",)),
    ("usb", "USB", ("USB_",), ()),
    ("swd", "SWD", ("SYS_JT",), ()),
    ("usart1", "USART1", ("USART1_",), ()),
    ("usart2", "USART2", ("USART2_",), ()),
    ("usart3", "USART3", ("USART3_",), ()),
    ("lpuart", "LPUART1", ("LPUART1_",), ()),
    ("uart5", "UART5", ("UART5_",), ()),
    ("leds", "LEDS", (), ("LED_",)),
    ("analog", "ANALOG", ("ADC",), ("V_SENSE", "CUR_SENSE")),
]

DISPLAY_SIGNAL = {"SYS_JTMS-SWDIO": "SYS_SWDIO", "SYS_JTCK-SWCLK": "SYS_SWCLK"}


def parse_ioc(path: Path) -> dict[str, dict[str, str]]:
    """Return {ioc_pin_name: {Signal:…, GPIO_Label:…, Mode:…}}."""
    pins: dict[str, dict[str, str]] = {}
    pat = re.compile(r"^(P[A-G]\d+(?:-[A-Z0-9_]+)?)\.(Signal|GPIO_Label|Mode)=(.*)$")
    for line in path.read_text(encoding="utf-8").splitlines():
        m = pat.match(line.strip())
        if m:
            pins.setdefault(m.group(1), {})[m.group(2)] = m.group(3).strip()
    return pins


def classify(name: str, info: dict[str, str] | None) -> tuple[str, str]:
    """Return (group_id, display_signal). group_id may be pwr/sys/nc."""
    if name in POWER_PINS:
        return "pwr", ""
    signal = (info or {}).get("Signal", "")
    label = (info or {}).get("GPIO_Label", "")
    if signal.startswith("RCC_OSC"):
        return "sys", signal
    if name in SYSTEM_ROLES and (not signal or signal == "GPIO_Input"):
        return "sys", SYSTEM_ROLES[name]
    if not signal:
        return "nc", ""
    for gid, _title, sig_prefixes, label_names in GROUPS:
        if any(signal.startswith(p) for p in sig_prefixes):
            return gid, label or DISPLAY_SIGNAL.get(signal, signal)
        if label and any(label.startswith(l) for l in label_names):
            return gid, label
    # Assigned but unrecognised: show it as its own catch-all so it is never hidden.
    return "other", label or signal


def load_pins(ioc: Path, package: str):
    layout = LAYOUTS.get(package)
    if layout is None:
        raise ValueError(f"unsupported MCU package: {package}")
    ioc_pins = parse_ioc(ioc)
    result = {}
    for side, names in layout.items():
        for idx, name in enumerate(names):
            info = ioc_pins.get(IOC_ALIASES.get(name, name))
            gid, display = classify(name, info)
            result[(side, idx)] = {
                "name": name,
                "group": gid,
                "display": display,
                "signal": (info or {}).get("Signal", ""),
                "label": (info or {}).get("GPIO_Label", ""),
            }
    return result


# ---------------------------------------------------------------- SVG output

# One fixed colour per bus group. The website version traces buses on hover;
# embedded as <img> in a README that interaction is gone, so colour does the
# job instead. Everything must stay readable on GitHub light AND dark themes:
# no currentColor, no near-black or near-white text, only mid-tone colours.
GROUP_COLORS = {
    "spi1": "#E0812F",
    "spi2": "#D63A4E",
    "i2c1": "#A06BDB",
    "motor": "#35A45F",
    "servo": "#BF5AF2",
    "pwm": "#C58B2A",
    "usb": "#D059A8",
    "swd": "#8B95A5",
    "usart1": "#3E8FD9",
    "usart2": "#16A8A0",
    "usart3": "#6D7FE0",
    "lpuart": "#2FB0C7",
    "uart5": "#E26D5A",
    "leds": "#A98514",
    "analog": "#66892B",
    "other": "#7D8590",
}

BASE_STYLE = """
#pinmap text{font-family:ui-monospace,'JetBrains Mono','Cascadia Mono',Consolas,monospace;}
#pinmap .pad{fill:none;stroke:#7D8590;stroke-opacity:.5;stroke-width:1;}
#pinmap .pad-txt{font-size:8px;font-weight:700;letter-spacing:.02em;fill:#7D8590;}
#pinmap .sig{font-size:10px;letter-spacing:.03em;fill:#7D8590;}
#pinmap .pad.nc{stroke-dasharray:3 3;stroke-opacity:.3;}
#pinmap .pad-txt.pwr,#pinmap .pad-txt.sys,#pinmap .pad-txt.nc{opacity:.8;font-weight:500;}
#pinmap .sig.sys{opacity:.8;}
#pinmap .chip-name{font-size:19px;font-weight:700;letter-spacing:.01em;fill:#AEB6C2;}
#pinmap .chip-pkg{font-size:12px;font-style:italic;fill:#6E7681;letter-spacing:.14em;}
""".strip()


def build_style() -> str:
    rules = [BASE_STYLE]
    for gid, color in GROUP_COLORS.items():
        rules.append(
            f"#pinmap .g-{gid} .pad{{fill:{color};stroke:none;}}"
            f"#pinmap .g-{gid} .pad-txt{{fill:#fff;}}"
            f"#pinmap .g-{gid} .sig{{fill:{color};}}"
        )
    return "\n".join(rules)


def pad_svg(side: str, idx: int, pin: dict, body_x: float, body_y: float, body_size: float) -> str:
    name, gid, disp = pin["name"], pin["group"], pin["display"]
    cls = gid if gid in ("pwr", "sys", "nc") else ""
    title = f"{name} · {disp}" if disp else name
    parts = [f"<g class=\"pin\"><title>{title}</title>"]
    if side in ("left", "right"):
        x = body_x - 42 if side == "left" else body_x + body_size
        y = body_y + 12.5 + idx * 20
        parts.append(f'<rect class="pad{" " + cls if cls else ""}" x="{x}" y="{y}" width="42" height="15" rx="3"/>')
        parts.append(f'<text class="pad-txt{" " + cls if cls else ""}" x="{x + 21}" y="{y + 10.3}" text-anchor="middle">{name}</text>')
        if disp:
            if side == "left":
                parts.append(f'<text class="sig{" sys" if cls == "sys" else ""}" x="{body_x - 50}" y="{y + 10.5}" text-anchor="end">{disp}</text>')
            else:
                parts.append(f'<text class="sig{" sys" if cls == "sys" else ""}" x="{body_x + body_size + 50}" y="{y + 10.5}" text-anchor="start">{disp}</text>')
    else:
        y = body_y - 42 if side == "top" else body_y + body_size
        x = body_x + 12.5 + idx * 20
        cx, cy = x + 7.5, y + 21
        parts.append(f'<rect class="pad{" " + cls if cls else ""}" x="{x}" y="{y}" width="15" height="42" rx="3"/>')
        parts.append(
            f'<text class="pad-txt{" " + cls if cls else ""}" x="{cx}" y="{cy}" text-anchor="middle" transform="rotate(-90 {cx} {cy})" dy="2.8">{name}</text>'
        )
        if disp:
            if side == "top":
                parts.append(f'<text class="sig{" sys" if cls == "sys" else ""}" x="{cx}" y="{body_y - 50}" text-anchor="start" transform="rotate(-90 {cx} {body_y - 50})" dy="3">{disp}</text>')
            else:
                parts.append(f'<text class="sig{" sys" if cls == "sys" else ""}" x="{cx}" y="{body_y + body_size + 50}" text-anchor="end" transform="rotate(-90 {cx} {body_y + body_size + 50})" dy="3">{disp}</text>')
    parts.append("</g>")
    return "".join(parts)


def build_svg(pins: dict, mcu_name: str, package: str) -> str:
    side_count = max(idx for _side, idx in pins) + 1
    body_size = side_count * 20 + 20
    body_x = 450 - body_size / 2
    body_y = 320 - body_size / 2

    plain, grouped = [], {}
    for (side, idx), pin in sorted(pins.items()):
        target = plain if pin["group"] in ("pwr", "sys", "nc") else grouped.setdefault(pin["group"], [])
        target.append(pad_svg(side, idx, pin, body_x, body_y, body_size))

    group_order = [gid for gid, *_ in GROUPS] + ["other"]
    titles = {gid: title for gid, title, *_ in GROUPS}
    titles["other"] = "OTHER"
    legend_y = body_y + 4
    legend_x = body_x + body_size + 155
    view_width = max(900, legend_x + 165)
    groups_svg = []
    for gid in group_order:
        if gid not in grouped:
            continue
        legend = (
            f'<g class="pin lg"><rect class="pad" x="{legend_x}" y="{legend_y}" width="16" height="16" rx="3"/>'
            f'<text class="sig" x="{legend_x + 24}" y="{legend_y + 11.5}" text-anchor="start">{titles[gid]}</text></g>'
        )
        groups_svg.append(f'<g class="grp g-{gid}" data-g="{gid}">{"".join(grouped[gid])}{legend}</g>')
        legend_y += 21.5

    return f"""<svg id="pinmap" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {view_width} 600" role="img" aria-label="{mcu_name} {package} pinout, colour-coded by bus.">
<style>
{build_style()}
</style>
<!-- chip body -->
<rect x="{body_x}" y="{body_y}" width="{body_size}" height="{body_size}" rx="14" fill="#14181F" stroke="#7D8590" stroke-opacity=".35"/>
<circle cx="{body_x + 22}" cy="{body_y + 22}" r="4.5" fill="none" stroke="#6E7681" stroke-width="1.5"/>
<text class="chip-name" x="450" y="318" text-anchor="middle">{mcu_name}</text>
<text class="chip-pkg" x="450" y="342" text-anchor="middle">{package}</text>
<g>{"".join(plain)}</g>
<g class="pins">
{chr(10).join(groups_svg)}
</g>
</svg>
"""


# ------------------------------------------------------------- README table

def build_table(pins: dict) -> str:
    titles = {gid: title for gid, title, *_ in GROUPS}
    titles.update({"pwr": "Power", "sys": "System", "other": "Other"})

    def port_key(p):
        m = re.match(r"P([A-G])(\d+)", p["name"])
        return (m.group(1), int(m.group(2))) if m else ("Z", 0)

    rows = []
    seen = set()
    for pin in sorted(pins.values(), key=port_key):
        if pin["name"] in seen or pin["name"] in POWER_PINS:
            continue
        seen.add(pin["name"])
        if pin["group"] == "nc" and pin["name"] not in SYSTEM_ROLES:
            continue
        func = pin["label"] or DISPLAY_SIGNAL.get(pin["signal"], pin["signal"]) or pin["display"]
        bus = titles.get(pin["group"], pin["group"])
        rows.append(f"| {pin['name']} | `{pin['signal'] or '-'}` | {func or '-'} | {bus} |")

    lines = [
        BEGIN_MARK,
        "",
        "![Pinout](documentation/pinout.svg)",
        "",
        "| Pin | Signal | Function | Bus |",
        "|-----|--------|----------|-----|",
        *rows,
        "",
        END_MARK,
    ]
    return "\n".join(lines)


def update_readme(table: str) -> None:
    text = README.read_text(encoding="utf-8")
    if BEGIN_MARK.split(" (")[0] in text and END_MARK in text:
        start = text.index(BEGIN_MARK.split(" (")[0])
        end = text.index(END_MARK) + len(END_MARK)
        text = text[:start] + table + text[end:]
    else:
        text = text.rstrip("\n") + "\n\n## Pinout\n\n" + table + "\n"
    README.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    iocs = sorted(FIRMWARE_DIR.glob("*.ioc"))
    if not iocs:
        print("error: no .ioc file found in firmware/", file=sys.stderr)
        return 1
    ioc = iocs[0]
    content = ioc.read_text(encoding="utf-8")
    mcu = re.search(r"^Mcu\.UserName=(.+)$", content, re.M)
    pkg = re.search(r"^Mcu\.Package=(.+)$", content, re.M)
    mcu_name = (mcu.group(1) if mcu else "STM32G474CEUx").strip()
    package = (pkg.group(1) if pkg else "UFQFPN48").strip()

    pins = load_pins(ioc, package)
    SVG_OUT.parent.mkdir(parents=True, exist_ok=True)
    SVG_OUT.write_text(build_svg(pins, mcu_name, package), encoding="utf-8", newline="\n")
    update_readme(build_table(pins))
    print(f"pinout: regenerated {SVG_OUT.relative_to(REPO_ROOT)} and README table from {ioc.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
